# -*- coding: utf-8 -*-
"""Noteboock_final_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ws70JCedmvYqDYIeGL0YF5thyfMn-1VN
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install numpy scikit-learn
!pip install micromlgen
!pip install geopandas osmnx leafmap
!pip install xgboost
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from numpy.lib.function_base import quantile
import matplotlib.pyplot as plt
import copy
from sklearn import preprocessing , tree
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor , ExtraTreesRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report ,  mean_squared_error, mean_absolute_error, r2_score
from sklearn.tree import DecisionTreeRegressor , DecisionTreeClassifier
from sklearn.impute import SimpleImputer
from xgboost import XGBRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from matplotlib import pyplot
from math import exp, expm1, pow
# %matplotlib inline
from matplotlib.pylab import rcParams
import seaborn as sns
rcParams['figure.figsize']=15,8
import matplotlib.image as mpimg
from micromlgen import port
from sklearn.svm import SVR
from tqdm import tqdm
import pickle

"""# **I - Préprocessing**

**Data_Irceline_Corroy-Le-Grand_All_bis(Données d'entrainement)**
"""

data_Irceline= pd.read_csv('Data_Irceline_Corroy-Le-Grand_All_bis.csv', parse_dates= {"datetime" : ["day","hour"]})
data_Irceline

"""## **I -2- Supession des colonnes "PM10" ; "PM2.5" et "datetime" et Convertion des valeurs de concentration de "NO2" et "O3" en PPM**"""

df_irceline = data_Irceline.drop(columns=['PM10', 'PM2.5'])

"""convert ug/m³ in ppm and ppm

- for CO : 1 ppb = 1.15 µg/m3
- for NO2: 1 ppb = 1.88 µg/m3
- for O3 : 1 ppb = 1.96 µg/m3
- 1 ppm = 1000 ppb
"""

#convert to ppb
df_irceline['NO2'] = df_irceline['NO2']/(1.88)
df_irceline['O3'] = df_irceline['O3']/(1.96)

#convert to ppm
df_irceline['NO2']= df_irceline['NO2']/1000
df_irceline['O3'] = df_irceline['O3']/1000
df_irceline['CO'] = df_irceline['CO']/1000

"""## **I-1 Quelques visualisations**"""

df = df_irceline.drop(columns=['windspeed', 'winddir', 'sealevelpressure', 'CO', 'datetime'])

print(df.describe())

print(df.info())

# Vérification des valeurs manquantes
print("Valeurs manquantes:\n", df_irceline.isnull().sum())

print("moyenne des valeurs manquantes en pourcent:\n", (df_irceline.isnull().mean(axis=0))*100)

# Calculer les coefficients de corrélation methode de pearson
correlation_matrix = df_irceline.corr()
# Vérifier la linéarité de chaque corrélation et imprimer la matrice de corrélation.
for column in correlation_matrix.columns:
    for index, value in correlation_matrix[column].items():
        if abs(value) >= 0.8:
            correlation_type = 'Relation linéaire forte'
        elif abs(value) >= 0.5:
            correlation_type = 'Relation linéaire modéré '
        elif abs(value) >= 0.3:
            correlation_type = 'Relations linéaires faibles'
        else:
            correlation_type = 'Pas de Relations linéaires'
        correlation_matrix.loc[index, column] = f'{value} ({correlation_type})'

# Imprimer la matrice de corrélation mise à jour
#print(correlation_matrix)

"""suite aux inforation recceulli sur les données du Data set,Il semble qu'il y ait des valeurs NaN (valeurs manquantes) dans le dataset,ce qui a provoqué une erreur lors de l'entraînement du modèle d'arbre de régression. Avant de procéder à l'entraînement, nous devons gérer ces valeurs manquantes. Il y a plusieurs approches pour cela :

- Supprimer les lignes avec des valeurs NaN : C'est l'approche la plus simple, mais elle peut entraîner une perte d'informations si beaucoup de lignes contiennent des valeurs NaN.
- Imputer les valeurs manquantes : Vous pouvez remplacer les valeurs NaN par des valeurs substituées, comme la moyenne, la médiane ou le mode de la colonne correspondante ou par la methode KNN.
- par Interpolation des variables

## **I -2-A Correction des NAN**

***NB: L’imputation par KNN permet une estimation précise et contextualisée des valeurs manquantes en se basant sur les instances les plus similaires, préservant ainsi les relations intrinsèques et la structure originale des données, ce qui est crucial pour les analyses complexes et les modèles prédictifs***
"""

# Configuration de l'imputeur KNN
imputer = KNNImputer(n_neighbors=5, weights="uniform")
df_1 = df[['NO2','O3', 'Temperature', 'Humidity']]
# Imputation des valeurs manquantes
df_imputed = pd.DataFrame(imputer.fit_transform(df_1))
df_imputed.columns = ['NO2', 'O3', 'Temperature', 'Humidity']
# Affichage après imputation
print("\nAprès imputation:\n", df_imputed)

print("moyenne des valeurs manquantes aprés imputation en pourcent:\n", (df_imputed.isnull().sum()))

"""**RMQ:** La concentration d'un gaz ne serait être négatif d'où il est important de vérifier si notre dataset n'en contient pas afin de correspondre a la realiter."""

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives = df_imputed.apply(lambda x: (x < 0).sum())
print("nombre de valeur negatives par feature:\n", nombre_valeurs_negatives)

"""## **I.2.B- Visualisation des donnees d'IRCELINE(donnee d'entraînement) après nettoyage**"""

# Calculer la matrice de corrélation
correlation_matrix = df_imputed.corr()

# Tracer la matrice de corrélation avec seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", square=True)
plt.title('Matrice de corrélation d_IRCELINE apres nettoyage')
plt.show()

pd.plotting.scatter_matrix(df_imputed, diagonal='kde')

"""**RMQ:** Ici nous réduisons notre dataset afin d'avoir que des données compris entre  '2021-05-10 00:00:00' et '2021-11-30 23:00:00'. Ceci dans le but de pouvoir faire des comparaisons immediate avec les données de Vocsens qui on été récolté a cette période"""

#Get measurements of the same periode as VOCSENS 2021-05-10 to 2021-11-30
df_ireceline_2021 = df_irceline[(df_irceline['datetime'] >= '2021-05-10 00:00:00') & (df_irceline['datetime'] <= '2021-11-30 23:00:00')]
#df_ireceline_2021

print("moyenne des valeurs manquantes en pourcent:\n", (df_ireceline_2021.isnull().sum()))

df_2021 = df_ireceline_2021.drop(columns=['windspeed', 'winddir', 'sealevelpressure', 'CO', 'datetime'])
# Configuration de l'imputeur KNN
imputer = KNNImputer(n_neighbors=5, weights="uniform")
df_2021 = df_2021[['NO2','O3', 'Temperature', 'Humidity']]
# Imputation des valeurs manquantes
df_imputed_2021 = pd.DataFrame(imputer.fit_transform(df_2021))
df_imputed_2021.columns = ['NO2', 'O3', 'Temperature', 'Humidity']
# Affichage après imputation
print("\nAprès imputation:\n", df_imputed_2021)

print("moyenne des valeurs manquantes en pourcent:\n", (df_imputed_2021.isnull().sum()))

pd.plotting.scatter_matrix(df_imputed_2021, diagonal='kde') #alpha is just relative or normalization percentage

df_imputed_2021.shape

"""# **II-Data_Vocsens(Données de test)**"""

df_vocsens= pd.read_csv('out10052022.csv', parse_dates= {"datetime" : ["timeStamp"]})
df_vocsens

"""## **II.1- Préprocessing**"""

# Description statistique
print(df_vocsens.describe())

# Calculer les coefficients de corrélation methode de pearson
correlation_matrix = df_vocsens.corr()

# Vérifier la linéarité de chaque corrélation et imprimer la matrice de corrélation.
for column in correlation_matrix.columns:
    for index, value in correlation_matrix[column].items():
        if abs(value) >= 0.8:
            correlation_type = 'Relation linéaire forte'
        elif abs(value) >= 0.5:
            correlation_type = 'Relation linéaire Modéré '
        elif abs(value) >= 0.3:
            correlation_type = 'Relation linéaire faible'
        else:
            correlation_type = 'pas de Relation linéaire'
        correlation_matrix.loc[index, column] = f'{value} ({correlation_type})'

# Imprimer la matrice de corrélation actualisée
print(correlation_matrix)

df_vocsens.isnull().sum()

#Conversion en données moyennes horaires comme celles de l'IRCELINE
df_HVoc=df_vocsens.resample('H', on='datetime', closed='right').mean().reset_index()
df_HVoc

df_HVoc.isnull().sum()

df = df_HVoc.drop(columns=['OX', 'NO', 'datetime'])
# Configuration de l'imputeur KNN
imputer = KNNImputer(n_neighbors=5, weights="uniform")
df_1 = df[['NO2','O3', 'Temperature', 'Humidity']]
# Imputation des valeurs manquantes
df_imputed_test = pd.DataFrame(imputer.fit_transform(df_1))
df_imputed_test.columns = ['NO2', 'O3', 'Temperature', 'Humidity']
# Affichage après imputation
print("\nAprès imputation:\n", df_imputed_test)

print("moyenne des valeurs manquantes en pourcent:\n", (df_imputed_test.isnull().sum()))

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives = df_imputed_test.apply(lambda x: (x < 0).sum())
print(nombre_valeurs_negatives)

# comme la première valeur de la colonne n'est pas négative, onpeut faire du forward fill

# Identifier les positions où la valeur est négative
mask = df_imputed_test['NO2'] < 0

# Appliquer un forward fill pour propager la dernière valeur valide (non-négative)
# Note: .ffill() ne modifie pas les valeurs déjà positives, il remplace seulement les NaN
df_imputed_test['NO2'] = df_imputed_test['NO2'].mask(mask).ffill()

df_imputed_test

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives = df_imputed_test.apply(lambda x: (x < 0).sum())
print(nombre_valeurs_negatives)

"""## **II.1.A Visualisation du dataset Vocsens**"""

pd.plotting.scatter_matrix(df_imputed_test, diagonal='kde')

# Calculer la matrice de corrélation
correlation_matrix = df_imputed_test.corr()

# Tracer la matrice de corrélation avec seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", square=True)
plt.title('Matrice de corrélation')
plt.show()

"""# **III- Comparaison des deux Datasets**"""

vocsens = np.array(df_imputed_test['NO2'][0:100])
ireceline = np.array(df_imputed_2021['NO2'][0:100])
# Plot outputs
plt.plot(vocsens, color='red', linewidth=2, label="NO2_Low-cost")
plt.plot(ireceline, 'g--', linewidth=3, label="NO2_IRCELINE")
plt.legend(loc="best")
plt.xlabel("Time")
plt.ylabel("NO2 (ppm)")
plt.title("Comparaison de concentration de NO2 des deux type de capteurs sur la même periode ")
plt.savefig("SimpleComparisionNO2.png", dpi=1200)
plt.show()

vocsens = np.array(df_imputed_test['NO2'][101:200])
ireceline = np.array(df_imputed_2021['NO2'][101:200])
# Plot outputs
plt.plot(vocsens, color='red', linewidth=2, label="NO2_Low-cost")
plt.plot(ireceline, 'g--', linewidth=3, label="NO2_IRCELINE")
plt.legend(loc="best")
plt.xlabel("Time")
plt.ylabel("NO2 (ppm)")
plt.title("Comparaison de concentration de NO2 des deux type de capteurs sur la même periode ")
plt.savefig("SimpleComparisionNO2.png", dpi=1200)
plt.show()

# Extracting data for plotting
vocsens = np.array(df_imputed_test['NO2'][945:962])
ireceline = np.array(df_imputed_2021['NO2'][945:962])

# Plot outputs in intervals of 100
# Plot outputs
plt.plot(vocsens, color='red', linewidth=2, label="NO2_Low-cost")
plt.plot(ireceline, 'g--', linewidth=3, label="NO2_IRCELINE")
plt.legend(loc="best")
plt.xlabel("Time")
plt.ylabel("NO2 (ppm)")
plt.title("Comparaison de concentration de NO2 des deux type de capteurs sur la même periode ")
plt.savefig("SimpleComparisionNO2.png", dpi=1200)
plt.show()

# Extracting data for plotting
vocsens = np.array(df_imputed_test['NO2'][:4900])
ireceline = np.array(df_imputed_2021['NO2'][:4900])

# Iteratively plot each segment of 100 points
for i in range(0, 4900, 200):
    plt.figure(figsize=(10, 6))
    plt.plot(vocsens[i:i+200], color='red', linewidth=2, label="NO2_Low-cost")
    plt.plot(ireceline[i:i+200], 'g--', linewidth=3, label="NO2_IRCELINE")
    plt.legend(loc="best")
    plt.xlabel("Time")
    plt.ylabel("NO2 (ppm)")
    plt.title(f"Comparaison de concentration de NO2 des deux types de capteurs sur la période {i} à {i+100}")
    plt.show()

vocsens = np.array(df_imputed_test['O3'][0:100])
ireceline = np.array(df_imputed_2021['O3'][0:100])
# Plot outputs
plt.plot(vocsens, color='red', linewidth=2, label="O3_Low-cost")
plt.plot(ireceline, 'g--', linewidth=3, label="O3_IRCELINE")
plt.legend(loc="best")
plt.xlabel("Time")
plt.ylabel("O3 (ppm)")
plt.title("Comparaison de concentration de O3 des deux type de capteurs sur la même periode ")
plt.savefig("SimpleComparisionNO2.png", dpi=1200)
plt.show()

"""# **IV- Développement de l’algorithme Extremely Randomized Trees**

## **IV.1- Calibration  et MAchine Learning**
"""

df_imputed

df_imputed_test

x_rf = df_imputed.drop(columns=['NO2'])  # Predictor variables
y_rf = df_imputed["NO2"]
x_rf_testing = df_imputed_test.drop(columns=['NO2'])  # Predictor variables
y_rf_testing = df_imputed_test["NO2"]

"""## **IV.2- IRCELINE (80%train et 20%test)**

**Calcul du R² manuellement**
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Division des données en ensembles d'entraînement et de test
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(x_rf, y_rf, test_size=0.2, random_state=42)

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)


# Calcul de la moyenne des valeurs réelles
y_mean = np.mean(y_rf_test)

# Calcul de la somme des carrés des résidus (SSE) et de la somme totale des carrés (SST)
sse = np.sum((y_rf_test - y_rf_pred_rf) ** 2)
sst = np.sum((y_rf_test - y_mean) ** 2)

# Calcul du coefficient de détermination (R²)
r_squared = 1 - (sse / sst)

print("Le coefficient de détermination (R²) calculé manuellement est:", r_squared)


print("Le sse est:", sse)
print("Le sst est:", sst)

"""**utilisation de sklearn**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Division des données en ensembles d'entraînement et de test
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(x_rf, y_rf, test_size=0.2, random_state=42)

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)
# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = msef(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

"""**j'essai un K-Fold validation**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
from sklearn.model_selection import cross_val_score, KFold


# Vos données ici, x_rf1 et y_rf1 devraient être définies au préalable
X = x_rf
y = y_rf

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Configuration de la validation croisée
cv = KFold(n_splits=5, random_state=42, shuffle=True)

# Calcul de la validation croisée pour différents scores
scores_mse = cross_val_score(rf, X, y, scoring='neg_mean_squared_error', cv=cv)
scores_rmse = cross_val_score(rf, X, y, scoring='neg_root_mean_squared_error', cv=cv)
scores_r2 = cross_val_score(rf, X, y, scoring='r2', cv=cv)

# Conversion des scores MSE et RMSE en valeurs positives
scores_mse = -scores_mse
scores_rmse = -scores_rmse

# Afficher les résultats
print("MSE par fold :", scores_mse)
print("MSE moyen :", np.mean(scores_mse))
print("RMSE par fold :", scores_rmse)
print("RMSE moyen :", np.mean(scores_rmse))
print("R^2 par fold :", scores_r2)
print("R^2 moyen :", np.mean(scores_r2))

"""## **IV.3- IRCELINE (train) et Vocsens(test)**"""

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(x_rf, y_rf)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(x_rf_testing)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = mean_squared_error(y_rf_testing, y_rf_pred_rf)
r2 = r2_score(y_rf_testing, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_testing, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

plt.figure(figsize=(10, 6))
plt.scatter(y_rf_testing, y_rf_pred_rf, alpha=0.5)
plt.plot([y_rf_testing.min(), y_rf_testing.max()], [y_rf_testing.min(), y_rf_testing.max()], 'k--', lw=4)  # Plotting a diagonal line where y=x
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs. Predicted')
plt.show()

y_rf_testing = np.random.normal(loc=50, scale=10, size=4900)  # Simulated actual values
y_rf_pred_rf = np.random.normal(loc=48, scale=10, size=4900)  # Simulated predicted values

# Iteratively plot each segment of 100 points
for i in range(0, 4900, 100):
    plt.figure(figsize=(10, 6))
    plt.plot(y_rf_testing[i:i+100], color='blue', linewidth=2, label="Actual Values")
    plt.plot(y_rf_pred_rf[i:i+100], 'r--', linewidth=3, label="Predicted Values")
    plt.legend(loc="best")
    plt.xlabel("Time Index")
    plt.ylabel("Value")
    plt.title(f"Comparison of Actual vs Predicted Values from Index {i} to {i+200}")
    plt.show()



from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Définir la grille des hyperparamètres à rechercher
param_grid = {
    'n_estimators': [20, 100, 300],  # Nombre d'arbres dans la forêt
    'max_depth': [None, 3, 10], # Profondeur maximale de chaque arbre
    'min_samples_split': [2, 5, 10], # Nombre minimum d'échantillons pour diviser un nœud
    'min_samples_leaf': [1, 2, 3], # Nombre minimum d'échantillons pour être à un nœud feuille
    'max_features': ['sqrt', 'log2'],
    'max_leaf_nodes': [None, 10],
}

# Instancier un objet GridSearchCV avec votre modèle de forêt aléatoire et la grille des paramètres
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')

# Ajuster GridSearchCV aux données d'entraînement
grid_search.fit(x_rf, y_rf)

# Obtenir le meilleur modèle trouvé par GridSearchCV
best_rf = grid_search.best_estimator_

# Prédiction sur l'ensemble de test avec le meilleur modèle
y_rf_pred_best = best_rf.predict(x_rf_testing)

# Calcul des métriques avec le meilleur modèle
mse_rf_best = mean_squared_error(y_rf_testing, y_rf_pred_best)
rmse_best = mean_squared_error(y_rf_testing, y_rf_pred_best, squared=False)
r2_best = r2_score(y_rf_testing, y_rf_pred_best)

print("Meilleur modèle trouvé par GridSearchCV:")
print(best_rf)
print("MSE_RF (meilleur modèle):", mse_rf_best)
print("RMSE_RF (meilleur modèle):", rmse_best)
print("R^2_RF (meilleur modèle):", r2_best)

# ici on essaye de comprendre pourquoi ont a un R² negatif

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(x_rf, y_rf)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(x_rf_testing)


# Calcul de la moyenne des valeurs réelles
y_mean = np.mean(y_rf_testing)

# Calcul de la somme des carrés des résidus (SSE) et de la somme totale des carrés (SST)
sse = np.sum((y_rf_testing - y_rf_pred_rf) ** 2)
sst = np.sum((y_rf_testing - y_mean) ** 2)

# Calcul du coefficient de détermination (R²)
r_squared = 1 - (sse / sst)

print("Le coefficient de détermination (R²) calculé manuellement est:", r_squared)


print("Le sse est:", sse)
print("Le sst est:", sst)

"""**RMQ:** on a sst qui tend vers 0 donc sse/sst va tendre ves l'infinid'ou 1 - inf = -inf . stt tend vers 0 car y_rf_testing devient  constant dans un certain interval. **Source**:'https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html'

## **IV.4- Vocsens (80%train et 20%test)**
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Division des données en ensembles d'entraînement et de test
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(x_rf_testing, y_rf_testing, test_size=0.2, random_state=42)

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = msef(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

###################################################################

"""# **V- Melange des deux dataset ( IRCELINE et Vocsens)**

## **V.1- Labelisation des types de capteur afin de les reconnaitre dans le mélange** 1 pour les low-cost de Vocsens et 0 pour IRCELINE
"""

df_HVoc1 = df_HVoc.copy(deep = True)
df_HVoc1 = df_HVoc1.drop(columns=['OX', 'NO'])
df_HVoc1['type_capteur'] = 1
df_HVoc1

df_irceline1 = df_irceline.copy(deep= True)
df_irceline1 = df_irceline1.drop(columns=['windspeed', 'winddir', 'sealevelpressure', 'CO'])
df_irceline1['type_capteur'] = 0
df_irceline1 = df_irceline1.loc[:,['datetime','Temperature', 'Humidity', 'NO2','O3', 'type_capteur']]
df_irceline1

"""## **V.2- Formation du nouveau dataset**"""

from sklearn.utils import shuffle

# Concaténation des DataFrames en un seul DataFrame
df_combined = pd.concat([df_irceline1, df_HVoc1], ignore_index=True)
#df_combined = pd.concat([df_entrain_meth1, df_HVoc_interpolation], axis=1)

# Utiliser la fonction shuffle pour mélanger les données
df_shuffled = shuffle(df_combined, random_state= 42).reset_index(drop=True)
#df_shuffled = shuffle(df_combined, random_state=42)  # Le random_state est optionnel pour la reproductibilité


print(df_shuffled)

"""### **V.2.A- Preprocessing**"""

#ce bout de code vas nous permettre de se rendre compte des doublon existant dans notre nouveaux dataset
df_sorted = (df_shuffled.sort_values(by='datetime')).reset_index(drop=True)
print(df_sorted.tail(1000))

new_data_train = df_shuffled.copy(deep = True)

new_data_train_sorted = (new_data_train.sort_values(by='datetime')).reset_index(drop=True)
print(new_data_train_sorted.tail(1000))

new_data_train.shape

dj = new_data_train_sorted.copy(deep=True)
df_unique = dj.drop_duplicates(subset=['datetime'],keep='first') # retire les doublons
print(df_unique.tail(1000))

df_unique

#Obtenir des mesures de la même période que VOCSENS 2021-05-10 à 2021-11-30
df_unique_2021 = df_unique[(df_unique['datetime'] >= '2021-05-10 00:00:00') & (df_unique['datetime'] <= '2021-11-30 23:00:00')]
df_unique_2021

# supprimer la colonne "datetime"
df_unique = df_unique.drop(columns=['datetime'])

# Vérification des valeurs manquantes
print("Valeurs manquantes:\n", df_unique.isnull().sum())

df = df_unique.copy(deep= True)
# Configuration de l'imputeur KNN
imputer = KNNImputer(n_neighbors=5, weights="uniform")
df_2 = df[['Temperature', 'Humidity', 'NO2','O3', 'type_capteur']]
# Imputation des valeurs manquantes
df_imputed1 = pd.DataFrame(imputer.fit_transform(df_2))
df_imputed1.columns = ['Temperature', 'Humidity', 'NO2','O3', 'type_capteur']
# Affichage après imputation
print("\nAprès imputation:\n", df_imputed1)

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives = df_imputed1.apply(lambda x: (x < 0).sum())

print(nombre_valeurs_negatives)

# nous remplacons les valeurs négatives par la dernière valeur positive précédente

# Étape 1: Identifier les positions où la valeur est négative
mask = df_imputed1['NO2'] < 0

# Étape 2: Appliquer un forward fill pour propager la dernière valeur valide (non-négative)
# Note: .ffill() ne modifie pas les valeurs déjà positives, il remplace seulement les NaN
df_imputed1['NO2'] = df_imputed1['NO2'].mask(mask).ffill()

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives = df_imputed1.apply(lambda x: (x < 0).sum())

print(nombre_valeurs_negatives)

# Vérification des valeurs manquantes
print("Valeurs manquantes:\n", df_imputed1.isnull().sum())

df_imputed1.shape

pd.plotting.scatter_matrix(df_imputed1[['Temperature', 'Humidity', 'NO2','O3']], diagonal='kde')

"""## **V.3- Application de notre Modele de ML**

### **V.3.A- En splitant le dataset mélangé en deux 80% pour l’entrainement et 20% pour les tests.**
"""

x_rf1 = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf1 = df_imputed1["NO2"]

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Division des données en ensembles d'entraînement et de test
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(x_rf1, y_rf1, test_size=0.2, random_state=42)

# Initialisation du modèle de forêt aléatoire
rf = ExtraTreesRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = msef(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
from sklearn.model_selection import cross_val_score, KFold


# Vos données ici, x_rf1 et y_rf1 devraient être définies au préalable
X = x_rf1
y = y_rf1

# Initialisation du modèle de forêt aléatoire
rf = ExtraTreesRegressor(n_estimators=100, random_state=42)

# Configuration de la validation croisée
cv = KFold(n_splits=5, random_state=42, shuffle=True)

# Calcul de la validation croisée pour différents scores
scores_mse = cross_val_score(rf, X, y, scoring='neg_mean_squared_error', cv=cv)
scores_rmse = cross_val_score(rf, X, y, scoring='neg_root_mean_squared_error', cv=cv)
scores_r2 = cross_val_score(rf, X, y, scoring='r2', cv=cv)

# Conversion des scores MSE et RMSE en valeurs positives
scores_mse = -scores_mse
scores_rmse = -scores_rmse

# Afficher les résultats
print("MSE par fold :", scores_mse)
print("MSE moyen :", np.mean(scores_mse))
print("RMSE par fold :", scores_rmse)
print("RMSE moyen :", np.mean(scores_rmse))
print("R^2 par fold :", scores_r2)
print("R^2 moyen :", np.mean(scores_r2))

from sklearn.model_selection import RandomizedSearchCV


# Division des données
X_train, X_test, y_train, y_test = train_test_split(x_rf1, y_rf1, test_size=0.2, random_state=42)

# Initialisation du modèle
rf = ExtraTreesRegressor(random_state=42)

# Paramètres à tester
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Recherche des meilleurs paramètres avec RandomizedSearchCV
random_search = RandomizedSearchCV(rf, param_grid, n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1, scoring='r2')
random_search.fit(X_train, y_train)

# Meilleur modèle
best_rf = random_search.best_estimator_

# Prédiction avec le meilleur modèle
y_pred = best_rf.predict(X_test)

# Calcul des métriques
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print("Meilleur modèle :", random_search.best_params_)
print("MSE_RF:", mse)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

y_rf = np.random.normal(loc=50, scale=10, size=4900)  # Simulated actual values
y_rf_pred_rf = np.random.normal(loc=48, scale=10, size=4900)  # Simulated predicted values

# Iteratively plot each segment of 100 points
for i in range(0, 4900, 100):
    plt.figure(figsize=(10, 6))
    plt.plot(y_rf_testing[i:i+100], color='blue', linewidth=2, label="Actual Values")
    plt.plot(y_rf_pred_rf[i:i+100], 'r--', linewidth=3, label="Predicted Values")
    plt.legend(loc="best")
    plt.xlabel("Time Index")
    plt.ylabel("Value")
    plt.title(f"Comparison of Actual vs Predicted Values from Index {i} to {i+200}")
    plt.show()

from sklearn.feature_selection import SelectFromModel

# Utilisation de SelectFromModel pour la sélection de caractéristiques
selector = SelectFromModel(best_rf, threshold='median')
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

# Entraînement du modèle sur les caractéristiques sélectionnées
best_rf.fit(X_train_selected, y_train)

# Nouvelle prédiction
y_pred_selected = best_rf.predict(X_test_selected)

# Nouvelle évaluation
r2_selected = r2_score(y_test, y_pred_selected)
print("R^2 avec sélection de caractéristiques :", r2_selected)

xtest = x_rf_testing.loc[:,['Temperature', 'Humidity','O3']]

print(xtest)

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Initialisation du modèle de forêt aléatoire
rf = ExtraTreesRegressor(n_estimators=500, random_state=42)

# Entraînement du modèle
rf.fit(x_rf1, y_rf1)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(xtest)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = mean_squared_error(y_rf, y_rf_pred_rf)
r2 = r2_score(y_rf, y_rf_pred_rf)
rmse = mean_squared_error(y_rf, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

from sklearn.model_selection import RandomizedSearchCV


# Initialisation du modèle
rf = ExtraTreesRegressor(random_state=42)

# Paramètres à tester
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Recherche des meilleurs paramètres avec RandomizedSearchCV
random_search = RandomizedSearchCV(rf, param_grid, n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1, scoring='r2')
random_search.fit(X_train, y_train)

# Meilleur modèle
best_rf = random_search.best_estimator_

# Prédiction avec le meilleur modèle
y_pred = best_rf.predict(xtest)

# Calcul des métriques
mse = mean_squared_error(y_rf_testing, y_pred)
r2 = r2_score(y_rf_testing, y_pred)
rmse = mean_squared_error(y_rf_testing, y_pred, squared=False)

print("Meilleur modèle :", random_search.best_params_)
print("MSE_RF:", mse)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

df_imputed_test['type_capteur'] = 1 # rajoute la colonne "type_capteur" a df_imputed_test
df_imputed_test = df_imputed_test.loc[:,['Temperature', 'Humidity', 'NO2','O3', 'type_capteur']]
df_imputed_test
t = df_imputed_test.drop(columns=['type_capteur'])

t.shape

"""### **V.3.B- retirer de Vocsens toutes les donnée qui se retrouve dans le dataset melangé**"""

p =  df_imputed1.loc[ df_imputed1['type_capteur'] == 1] # retoune dataframe shluffé juste avec les capteurs de type 1
p= p.reset_index(drop=True)
p = p.drop(columns=['type_capteur'])
#unique_to = df_imputed_test[~df_imputed_test.isin(p).all(axis=1)] #Trouver des lignes dans df_imputed_test qui ne sont pas dans p retourne un dataframe ou aucune valeur du dataset melanger ne se trouve a l'interieur
#unique_to = t[~t.isin(p).all(axis=1)]
#unique_to = p[~p.isin(df_imputed_test).all(axis=1)]

# Supposons que df_imputed_test et p sont vos DataFrames
# Nous assumons également que toutes les colonnes doivent correspondre pour identifier les duplicatas

# Utilisation de merge pour identifier les lignes communes en supposant que les deux DataFrames ont les mêmes colonnes
common = df_imputed_test.merge(p, indicator=True, how='outer')

# Filtrer pour conserver uniquement les lignes qui n'apparaissent que dans df_imputed_test
unique_to = common[common['_merge'] == 'left_only'].drop(columns=['_merge'])

# unique_to contiendra maintenant les données de df_imputed_test sans les entrées présentes dans p qui est le dataset melangé
print(unique_to)

from google.colab import files
# Sauvegarde du DataFrame dans un fichier CSV
p.to_csv('p.csv', index=False)
files.download('p.csv')

p

from google.colab import files
# Sauvegarde du DataFrame dans un fichier CSV
unique_to.to_csv('data_test.csv', index=False)
files.download('data_test.csv')

unique_to

#unique_to = unique_to.loc[:,['Temperature', 'Humidity', 'NO2','O3', 'type_capteur']]
#unique_to # nos nouvelles données de test

"""### **entrainent sur les données melangé et en testant avec les nonnées de Vocsens ne se trouvant pas dans le melage"unique_to".**"""

X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]

# Initialisation du modèle de forêt aléatoire
rf = ExtraTreesRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = mean_squared_error(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

y_rf_test = np.random.normal(loc=50, scale=10, size=4900)  # Simulated actual values
y_rf_pred_rf = np.random.normal(loc=48, scale=10, size=4900)  # Simulated predicted values

# Iteratively plot each segment of 100 points
for i in range(0, 4900, 50):
    plt.figure(figsize=(10, 6))
    plt.plot(y_rf_testing[i:i+50], color='blue', linewidth=2, label="Actual Values")
    plt.plot(y_rf_pred_rf[i:i+50], 'r--', linewidth=3, label="Predicted Values")
    plt.legend(loc="best")
    plt.xlabel("Time Index")
    plt.ylabel("Value")
    plt.title(f"Comparison of Actual vs Predicted Values from Index {i} to {i+200}")
    plt.show()

"""## **Élagage et Contrôle de la Profondeur**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]

# Adjusting the model with pruning and depth control
model_pruned = ExtraTreesRegressor(
    max_depth=20,                 # Reducing depth
    min_samples_split=10,         # Higher number means less splitting
    min_samples_leaf=4,           # Fewer splits at the leaf level
    random_state=42
)

# Fit the model on training data
model_pruned.fit(X_rf_train, y_rf_train)

# Predict on test data
predictions_pruned = model_pruned.predict(X_rf_test)

# Calculate metrics
mse_pruned = mean_squared_error(y_rf_test, predictions_pruned)
rmse_pruned = mse_pruned ** 0.5
r2_pruned = r2_score(y_rf_test, predictions_pruned)

print("MSE:", mse_pruned)
print("RMSE:", rmse_pruned)
print("R² Score:", r2_pruned)

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
from sklearn.model_selection import RandomizedSearchCV
X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]

# Initialisation du modèle
rf = ExtraTreesRegressor(random_state=42)

# Paramètres à tester
param_grid = {
    'n_estimators': [50, 100, 200, 300, 400],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [None, 5, 10, 20, 30, 50],
    'min_samples_split': [2, 5, 10, 30, 50],
    'min_samples_leaf': [1, 2, 4, 10, 15]
}

# Recherche des meilleurs paramètres avec RandomizedSearchCV
random_search = RandomizedSearchCV(rf, param_grid, n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1, scoring='r2')
random_search.fit(X_rf_train, y_rf_train)

# Meilleur modèle
best_rf = random_search.best_estimator_

# Prédiction avec le meilleur modèle
y_pred = best_rf.predict(X_rf_test)

# Calcul des métriques
mse = mean_squared_error(y_rf_test, y_pred)
r2 = r2_score(y_rf_test, y_pred)
rmse = mean_squared_error(y_rf_test, y_pred, squared=False)

print("Meilleur modèle :", random_search.best_params_)
print("MSE_RF:", mse)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

"""# **Application du gridsearch**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Définir la grille des hyperparamètres à rechercher
param_grid = {
    'n_estimators': [20, 100],  # Nombre d'arbres dans la forêt
    'max_depth': [None, 3, 4], # Profondeur maximale de chaque arbre
    'min_samples_split': [2, 5, 10], # Nombre minimum d'échantillons pour diviser un nœud
    'min_samples_leaf': [1, 2, 3], # Nombre minimum d'échantillons pour être à un nœud feuille
    'max_features': ['sqrt', 'log2'],
    'max_leaf_nodes': [None, 10, 20],
}

# Instancier un objet GridSearchCV avec votre modèle de forêt aléatoire et la grille des paramètres
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')

# Ajuster GridSearchCV aux données d'entraînement
grid_search.fit(X_rf_train, y_rf_train)

# Obtenir le meilleur modèle trouvé par GridSearchCV
best_rf = grid_search.best_estimator_

# Prédiction sur l'ensemble de test avec le meilleur modèle
y_rf_pred_best = best_rf.predict(X_rf_test)

# Calcul des métriques avec le meilleur modèle
mse_rf_best = mean_squared_error(y_rf_test, y_rf_pred_best)
rmse_best = mean_squared_error(y_rf_test, y_rf_pred_best, squared=False)
r2_best = r2_score(y_rf_test, y_rf_pred_best)

print("Meilleur modèle trouvé par GridSearchCV:")
print(best_rf)
print("MSE_RF (meilleur modèle):", mse_rf_best)
print("RMSE_RF (meilleur modèle):", rmse_best)
print("R^2_RF (meilleur modèle):", r2_best)

#################################################################### Visualisation ################################################################################

df_unique_2021_1 = df_unique_2021.drop(columns=['type_capteur']).reset_index(drop=True)
df_unique_2021_1

#df_HVoc = df_HVoc.drop(columns=['type_capteur', 'OX', 'NO'])
#df_HVoc

plt.plot(np.array(df_HVoc['NO2'][1700:1850]), color='red', linewidth=2, label="baseline_NO2_ppm_LCS")
plt.plot(np.array(df_unique_2021_1['NO2'][1700:1850]), 'b--', linewidth=3, label="baseline_NO2_ppm_HCS")
plt.legend(loc="best")
plt.xlabel("Timestamps (H)")
plt.ylabel("NO2 (ppm)")
#plt.title("Multiple Linear Regression Prediction")
#plt.savefig("Figures_ACM_paper/Baseline_BeforeML.png", dpi=600)
plt.show()

fig, ax = plt.subplots()
ax.boxplot([df_HVoc['NO2'][4600:4900], df_unique_2021_1['NO2'][4601:4901]], labels=['Dataset 1', 'Dataset 2'])
ax.set_title('Box Plot Comparaison')
ax.set_ylabel('Valeurs')
plt.show()

# Supposition de la structure de DataFrame et extraction des données
a = df_HVoc['NO2'].to_numpy().reshape(-1, 1)  # reformer en 2D si nécessaire
b = df_unique_2021_1['NO2'].to_numpy().reshape(-1, 1)  # reformer en 2D si nécessaire

# Création de la figure et des axes pour les heatmaps
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))

# Dessin des heatmaps
sns.heatmap(a, ax=ax1, cmap='viridis')
sns.heatmap(b, ax=ax2, cmap='viridis')

# Définition des titres
ax1.set_title('Dataset 1')
ax2.set_title('Dataset 2')

# Affichage du plot
plt.show()

# Entraîner le modèle RandomForestRegressor (si ce n'est pas déjà fait)
rf.fit(X_rf_train, y_rf_train)

# Obtenir l'importance des caractéristiques
feature_importance = rf.feature_importances_

# Obtenez le nom des caractéristiques
feature_names = X_rf_train.columns

# Tracer le diagramme à barres de l'importance des caractéristiques
plt.figure(figsize=(10, 6))
plt.barh(feature_names, feature_importance)
plt.xlabel('Importance des caractéristiques')
plt.ylabel('Caractéristiques')
plt.title('Importance des caractéristiques dans RandomForestRegressor')
plt.show()

# Créer une liste des données à visualiser (par exemple, les résidus)
data_to_plot = [y_rf_test - y_rf_pred_rf]  # Si vous voulez tracer les résidus

# Créer un diagramme en boîte
plt.figure(figsize=(8, 6))
plt.boxplot(data_to_plot)
plt.xticks([1], ['Résidus'])  # Renommer l'axe x si nécessaire
plt.ylabel('Valeurs')  # Ajouter une étiquette à l'axe y
plt.title('Diagramme en boîte des résidus')  # Ajouter un titre
plt.grid(True)  # Activer la grille si nécessaire
plt.show()

# Créer le scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(y_rf_pred_rf, y_rf_test, alpha=0.5)  # alpha définit la transparence des points
plt.xlabel('Valeurs prédites')
plt.ylabel('Valeurs réelles')
plt.title('Diagramme de dispersion des valeurs prédites vs valeurs réelles')
plt.grid(True)  # Activer la grille si nécessaire
plt.show()

# Créer le scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(y_rf_pred_rf, y_rf_test, alpha=0.5)  # alpha définit la transparence des points
plt.plot([min(y_rf_pred_rf), max(y_rf_pred_rf)], [min(y_rf_test), max(y_rf_test)], color='red', linestyle='--')
plt.xlabel('Valeurs prédites')
plt.ylabel('Valeurs réelles')
plt.title('Diagramme de dispersion des valeurs prédites vs valeurs réelles')
plt.grid(True)  # Activer la grille si nécessaire
plt.show()

# Combiner les caractéristiques indépendantes et la variable cible dans un seul DataFrame
df_combined = X_rf_train.copy()  # Copier les caractéristiques indépendantes
df_combined['NO2'] = y_rf_train  # Ajouter la variable cible

# Calculer la matrice de corrélation
correlation_matrix = df_combined.corr()

# Tracer la matrice de corrélation avec seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", square=True)
plt.title('Matrice de corrélation')
plt.show()

"""Pour ajuster le modèle de Random Forest Regressor en ajoutant des contraintes, nous pouvons modifier certains paramètres pour éviter un surajustement et potentiellement améliorer les performances sur l'ensemble de test. Voici quelques paramètres que nous pourrions ajuster :

- n_estimators : Augmenter le nombre d'arbres peut améliorer la performance du modèle jusqu'à un certain point, mais cela augmente aussi le temps de calcul.
- max_depth : Réduire la profondeur maximale de chaque arbre peut aider à prévenir le surajustement.
- min_samples_split : Augmenter le nombre minimum d'échantillons requis pour diviser un nœud interne.
- min_samples_leaf : Augmenter le nombre minimum d'échantillons requis pour être à un nœud feuille.
- max_features : Réduire le nombre de caractéristiques à considérer lors de la recherche de la meilleure division peut aider à rendre le modèle plus robuste.
"""

from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
X_rf_train =  p.drop(columns=['NO2'])
X_rf_test = unique_to.drop(columns=['NO2', "type_capteur"])
y_rf_train = p["NO2"]
y_rf_test = unique_to["NO2"]
# Ajustement du modèle en réduisant max_depth
rf_model_reduced_depth = ExtraTreesRegressor(n_estimators=200, # Nombre d'arbres
                                               max_depth=15, # Réduction de la profondeur de chaque arbre
                                               min_samples_split=10, # Nombre minimum d'échantillons pour diviser un nœud
                                               min_samples_leaf=4, # Nombre minimum d'échantillons pour être à un nœud feuille
                                               max_features='sqrt', # Nombre de caractéristiques à considérer pour la meilleure division
                                               random_state=42)

# Entraînement du modèle ajusté avec une profondeur réduite
rf_model_reduced_depth.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test avec le modèle à profondeur réduite
y_pred_reduced_depth = rf_model_reduced_depth.predict(X_rf_test)

# Évaluation du modèle à profondeur réduite
mse_reduced_depth = mean_squared_error(y_rf_test, y_pred_reduced_depth)
mae_reduced_depth = mean_absolute_error(y_rf_test, y_pred_reduced_depth)
r2_reduced_depth = r2_score(y_rf_test, y_pred_reduced_depth)

mse_reduced_depth, mae_reduced_depth, r2_reduced_depth

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
X_rf_train =  p.drop(columns=['NO2'])
X_rf_test = unique_to.drop(columns=['NO2', "type_capteur"])
y_rf_train = p["NO2"]
y_rf_test = unique_to["NO2"]
model = ExtraTreesRegressor(random_state=42)

# Définition de la distribution des paramètres
param_dist = {
    'n_estimators': randint(100, 500),
    'max_depth': [10, 20, None],
    'min_samples_split': randint(2, 11),
    'min_samples_leaf': randint(1, 5),
    'max_features': ['sqrt', 'log2'],
    'max_leaf_nodes': [None, 10, 20, 30],
}

# Recherche aléatoire des meilleurs hyperparamètres avec RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, n_iter=100, cv=5, scoring='neg_mean_squared_error', random_state=42, n_jobs=-1)
random_search.fit(X_rf_train, y_rf_train)

# Meilleurs hyperparamètres
best_params = random_search.best_params_
print("Meilleurs hyperparamètres:", best_params)

# Modèle final avec les meilleurs hyperparamètres
best_model = random_search.best_estimator_

# Évaluation du modèle
y_pred = best_model.predict(X_rf_test)
mse = mean_squared_error(y_rf_test, y_pred)
r2 = r2_score(y_rf_test, y_pred_reduced_depth)
print("Erreur quadratique moyenne (MSE):", mse)
print("Erreur quadratique moyenne (r2):", r2)

"""# **Contrainte  Expert**"""

X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]
# Appliquer la règle : Si la température est inférieure à 5°C, l'effet de l'humidité sur NO2 est doublé
X_rf_train['temp_humidity_interaction'] = X_rf_train.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)
X_rf_test['temp_humidity_interaction'] = X_rf_test.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=300, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = mean_squared_error(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)



def apply_threshold_constraint(predictions, threshold):
    """
    Applique une contrainte de seuil sur les prédictions de NO2.
    Si la valeur prédite dépasse le seuil, elle est remplacée par le seuil lui-même.
    """
    return [prediction if prediction <= threshold else threshold for prediction in predictions]


# Définir un seuil de concentration de NO2
seuil_concentration_NO2 = 50  # Exemple de seuil de 50 µg/m³

# Appliquer la contrainte de seuil sur les prédictions du modèle
y_rf_pred_rf_constrained = apply_threshold_constraint(y_rf_pred_rf, seuil_concentration_NO2)

# Calculer les métriques d'évaluation avec la contrainte de seuil
mse_rf_constrained = mean_squared_error(y_rf_test, y_rf_pred_rf_constrained)
rmse_constrained = mean_squared_error(y_rf_test, y_rf_pred_rf_constrained, squared=False)
r2_constrained = r2_score(y_rf_test, y_rf_pred_rf_constrained)

# Afficher les métriques
print("MSE_RF avec contrainte de seuil:", mse_rf_constrained)
print("RMSE_RF avec contrainte de seuil:", rmse_constrained)
print("R^2_RF avec contrainte de seuil:", r2_constrained)

"""# **Combinaison entre contrainte venant de l'expert et la contrainte structurel**"""

# Définir les modèles et leurs grilles d'hyperparamètres respectives
X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]



# Appliquer la règle : Si la température est inférieure à 5°C, l'effet de l'humidité sur NO2 est doublé
X_rf_train['temp_humidity_interaction'] = X_rf_train.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)
X_rf_test['temp_humidity_interaction'] = X_rf_test.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)

# Réentraînement du modèle de Random Forest avec la nouvelle caractéristique
rf_model_with_expert = RandomForestRegressor(n_estimators=400, # Nombre d'arbres
                                             max_depth=8, # Réduire la profondeur maximale de chaque arbre
                                             min_samples_split=25, # Augmenter le nombre minimum d'échantillons pour diviser un nœud
                                             min_samples_leaf=12, # Augmenter le nombre minimum d'échantillons pour être à un nœud feuille
                                             max_features='sqrt', # Nombre de caractéristiques à considérer pour la meilleure division
                                             random_state=42)

# Entraînement du modèle ajusté avec la nouvelle caractéristique
rf_model_with_expert.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test avec la nouvelle caractéristique
y_pred_with_expert = rf_model_with_expert.predict(X_rf_test)

# Évaluation du modèle avec la nouvelle caractéristique
mse_with_expert = mean_squared_error(y_rf_test, y_pred_with_expert)
r2 = r2_score(y_rf_test, y_pred_with_expert)
rmse = mean_squared_error(y_rf_test, y_pred_with_expert, squared=False)
print("MSE_RF:", mse_rf)
print("R^2_RF:", r2)
print("RMSE_RF:", rmse)

from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
# Définir les modèles et leurs grilles d'hyperparamètres respectives
X_rf_train = df_imputed1.drop(columns=['NO2', 'type_capteur'])  # Predictor variables
y_rf_train = df_imputed1["NO2"]
X_rf_test = unique_to.drop(columns=['NO2', 'type_capteur'])
y_rf_test = unique_to["NO2"]
models = {
    'Linear Regression': (LinearRegression(), {}),
    'Random Forest': (RandomForestRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Extremely Randomized Trees': (ExtraTreesRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Decision Tree': (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}),
    'Gradient Boosting': (GradientBoostingRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'learning_rate': [0.1, 0.01, 0.001]})
}

# Créer des dictionnaires vides pour stocker les meilleurs modèles, leurs métriques d'évaluation et les paramètres utilisés
best_models = {}
best_rmse = {}
best_r2 = {}
used_parameters = {}

# Effectuer un grid search pour chaque modèle
for model_name, (model, param_grid) in models.items():
    grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')

    #
    with tqdm(total=len(param_grid), desc=f"Grid Search ({model_name})", unit="param") as pbar:
        grid_search.fit(X_rf_train, y_rf_train)

        # Save the best model
        best_models[model_name] = grid_search.best_estimator_

        # Save the used parameters
        used_parameters[model_name] = grid_search.best_params_

        # Predict on the test set
        y_pred = grid_search.predict(X_rf_test)

        # Calculate evaluation metrics
        mse = msef(y_rf_test, y_pred)
        rmse = np.sqrt(mse)
        mae = maef(y_rf_test, y_pred)
        r2 = r2_score(y_rf_test, y_pred)

        # Store the evaluation metrics
        best_rmse[model_name] = rmse
        best_r2[model_name] = r2

        # Print the evaluation metrics
        print(f"Model: {model_name}")
        print("Best Hyperparameters:", grid_search.best_params_)
        print("MSE:", mse)
        print("RMSE:", rmse)
        print("MAE:", mae)
        print("R2 Score:", r2)
        print()

        # Update the progress bar
        pbar.update()

# Sort the best models based on RMSE and R2 score
sorted_models_by_rmse = sorted(best_models.items(), key=lambda x: best_rmse[x[0]])
sorted_models_by_r2 = sorted(best_models.items(), key=lambda x: best_r2[x[0]])

# Print the best models sorted by RMSE
print("Best Models (sorted by RMSE):")
for model_name, model in sorted_models_by_rmse:
    print(f"{model_name}: RMSE = {best_rmse[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

# Print the best models sorted by R2 score
print("\nBest Models (sorted by R2 Score):")
for model_name, model in sorted_models_by_r2:
    print(f"{model_name}: R2 Score = {best_r2[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

############################ FIN FIN FIN FIN ####################################################""""

"""**A-2- Processus 2** on fait un fillna ( on remplace les valeurs manquantes par des 0)"""

df_irceline_fillna = df_irceline.copy(deep=True)

# remplacer les valeur NAN par 0
df_irceline_fillna['NO2']=df_irceline_fillna['NO2'].fillna(0)
df_irceline_fillna['O3']=df_irceline_fillna['O3'].fillna(0)
df_irceline_fillna['CO']=df_irceline_fillna['CO'].fillna(0)
df_irceline_fillna['Temperature']=df_irceline_fillna['Temperature'].fillna(0)
df_irceline_fillna['Humidity']=df_irceline_fillna['Humidity'].fillna(0)
df_irceline_fillna['windspeed']=df_irceline_fillna['windspeed'].fillna(0)
df_irceline_fillna['winddir']=df_irceline_fillna['winddir'].fillna(0)
df_irceline_fillna['sealevelpressure']=df_irceline_fillna['sealevelpressure'].fillna(0)

df_irceline_fillna.isnull().sum()

"""**A-3- Processus 3** on fait un dropna ( on suprime toutes les ligne contenant ne serais qu'une valeur nan)"""

df_irceline_dropna = df_irceline.copy(deep=True)

df_irceline_dropna = df_irceline_dropna.dropna()

df_irceline_dropna.isnull().sum()

"""**`NB :`** dans un premier temps je vais travailler avec un dataset ou dans un premier temps j'aifais de l'interpolation et pour les 18 chaque autre valeur NAN des colonnes NO2, CO, O3 on été mis a 0.

**Data_Vocsens(Données de test)**
"""

df_vocsens= pd.read_csv('out10052022.csv', parse_dates= {"datetime" : ["timeStamp"]})
df_vocsens

#Convert to hourly average data as those of IRCELINE
df_HVoc=df_vocsens.resample('H', on='datetime', closed='right').mean().reset_index()
df_HVoc

df_HVoc.isnull().sum()

"""**B-1- Processus 1** on fait une interpolation"""

df_HVoc_interpolation = df_HVoc.copy(deep=True)

df_HVoc_interpolation['Temperature']= df_HVoc_interpolation['Temperature'].interpolate(method='polynomial', order=2)
df_HVoc_interpolation['Humidity']= df_HVoc_interpolation['Humidity'].interpolate(method='polynomial', order=2)
df_HVoc_interpolation['NO2']= df_HVoc_interpolation['NO2'].interpolate(method='polynomial', order=2)
df_HVoc_interpolation['OX']= df_HVoc_interpolation['OX'].interpolate(method='polynomial', order=2)
df_HVoc_interpolation['NO']= df_HVoc_interpolation['NO'].interpolate(method='polynomial', order=2)
df_HVoc_interpolation['O3']= df_HVoc_interpolation['O3'].interpolate(method='polynomial', order=2)

df_HVoc_interpolation.isnull().sum()

"""**B-2- Processus 2** on fait un fillna ( on remplace toutes les valeurs NAN par 0)"""

df_HVoc_fillna = df_HVoc.copy(deep=True)

# remplacer les valeur NAN par 0
df_HVoc_fillna['Temperature']= df_HVoc_fillna['Temperature'].fillna(0)
df_HVoc_fillna['Humidity']= df_HVoc_fillna['Humidity'].fillna(0)
df_HVoc_fillna['NO2']= df_HVoc_fillna['NO2'].fillna(0)
df_HVoc_fillna['OX']= df_HVoc_fillna['OX'].fillna(0)
df_HVoc_fillna['NO']= df_HVoc_fillna['NO'].fillna(0)
df_HVoc_fillna['O3']= df_HVoc_fillna['O3'].fillna(0)

df_HVoc_fillna.isnull().sum()

"""**B-3- Processus 3** on fait un dropna ( on suprime toutes les lignes contenant ne serait-ce qu'une valeur NAN )"""

df_HVoc_dropna = df_HVoc.copy(deep=True)

df_HVoc_dropna = df_HVoc_dropna.dropna()

df_HVoc_dropna.isnull().sum()

"""**# II- Visualisation**"""

#visualisation du NO2 pour les données de train et de test sans ML

plt.plot(np.array(df_HVoc['NO2'][1700:1850]), color='red', linewidth=2, label="baseline_NO2_ppm_LCS")
plt.plot(np.array(df_ireceline_2021['NO2'][1700:1850]), 'b--', linewidth=3, label="baseline_NO2_ppm_HCS")
plt.legend(loc="best")
plt.xlabel("Timestamps (H)")
plt.ylabel("NO2 (ppm)")
#plt.title("Multiple Linear Regression Prediction")
#plt.savefig("Figures_ACM_paper/Baseline_BeforeML.png", dpi=600)
plt.show()

#comparison using two y axis
x = np.arange(0, 30.0, 0.1)
y1 = np.array(df_HVoc['NO2'][4600:4900])
y2 = np.array(df_ireceline_2021['NO2'][4601:4901])

fig, ax1 = plt.subplots()

ax2 = ax1.twinx()
ax1.plot(x, y1, 'g-')
ax2.plot(x, y2, 'b-')

ax1.set_xlabel('X data')
ax1.set_ylabel('NO2 VocSens', color='g')
ax2.set_ylabel('NO2 Irceline', color='b')

plt.show()

"""**Calcule des metriques MSE, RMSE et MAE sans ML**

# **III- Mise en place des Modèles**

**NB:** dans un premier temps je vais juste travailler avec les données d'irceline  que je vais spliter en train_set et test_set et je vais travailler avec un dataset ou dans un premier temps j'aifais de l'interpolation et pour les 18 chaque autre valeur NAN des colonnes NO2, CO, O3 on été mis a 0. " df_irceline_nan_in_0"
"""

#nous ne nous soucions pas de la date (pas de prévision dans notre problématique)
training_data_meth1 = df_irceline_nan_in_0.drop(labels='datetime', axis=1)

training_data_meth1

data_entrain_meth1= training_data_meth1.drop(['CO', 'windspeed', 'winddir', 'sealevelpressure'],axis=1)
data_entrain_meth1

"""**Rmq:** Puisque la concentration reflète la présence réelle d'une substance dans un mélange, et qu'une quantité de substance ne peut pas être moins que zéro (ce qui impliquerait une absence totale et même au-delà), les valeurs négatives de concentration ne sont pas physiquement possibles. Une valeur négative indiquerait non seulement l'absence de la substance mais aussi quelque chose de physiquement irréalisable dans le contexte des lois de la chimie et de la physique. On a affaire ici soit à une erreur de: mesure, calcul ou transcription."""

# on compte le nombre de valeur negative dans chacune de colonnes
nombre_valeurs_negatives_meth1 = data_entrain_meth1.apply(lambda x: (x < 0).sum())

print(nombre_valeurs_negatives_meth1)

# on remplace chaque valeur negative par 0 / je pensais aussi a la possibilité de les suprimer
data_entrain_meth1['O3'] = data_entrain_meth1['O3'].apply(lambda x : x if x > 0 else 0)
data_entrain_meth1['NO2'] = data_entrain_meth1['NO2'].apply(lambda x : x if x > 0 else 0)

print("Valeurs negative:\n", data_entrain_meth1.apply(lambda x: (x < 0).sum()))

"""**Rmq:** a fin de faire corespondre au mieux nos données d'entrainement a nos de test, je vais faire une permutation de l'odre des colonnes."""

df_entrain_meth1 = data_entrain_meth1.copy(deep=True)

df_entrain_meth1 = df_entrain_meth1.loc[:,['Temperature', 'Humidity', 'NO2','O3']]
df_entrain_meth1

y_training_meth1 = df_entrain_meth1["NO2"]
x_training_meth1 = df_entrain_meth1.drop('NO2', axis=1)
print("X_training: ",x_training_meth1.shape)
print("y_training: ",y_training_meth1.shape)

x_training_meth1.isnull().sum()

"""**premier model d'extra_tree**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
X_t, X_ts, y_t, y_ts = train_test_split(x_training_meth1, y_training_meth1, test_size=0.3, random_state=42)

# Création et formation du modèle Extra Trees
extra_trees_model = ExtraTreesRegressor(random_state=42)
extra_trees_model.fit(X_t, y_t)

# Faire des prédictions et évaluer le modèle
y3_pred_extra_trees = extra_trees_model.predict(X_ts)
mse_extra_trees = msef(y_ts, y3_pred_extra_trees)
r2_extra_trees = r2_score(y_ts, y3_pred_extra_trees)
rmse_extra_trees = msef(y_ts, y3_pred_extra_trees, squared=False)

print("MSE_ExTree:", mse_extra_trees)
print("R^2_ExTree:", r2_extra_trees)
print("RMSE_ExTree:", rmse_extra_trees)

"""**Calcule du R² sans appel a la fontion r2_score(x,y) de sciklearn**"""

X_train, X_test, y_train, y_test = train_test_split(x_training_meth1, y_training_meth1, test_size=0.3, random_state=42)

# Création et entraînement du modèle d'arbre de régression sur des données imputées
regressor = DecisionTreeRegressor(random_state=42)
regressor.fit(X_train, y_train)

#
y_pred = regressor.predict(X_test)


y = y_test
# Calcul de la moyenne des valeurs réelles
y_mean = np.mean(y)

# Calcul de la somme des carrés des résidus (SSE) et de la somme totale des carrés (SST)
sse = np.sum((y - y_pred) ** 2)
sst = np.sum((y - y_mean) ** 2)
print("Le sse est:", sse)
print("Le sst est:", sst)
# Calcul du score R^2
r2_score = 1 - (sse / sst)

print("Le score R^2 est:", r2_score)
# Evaluating the model
#mse_et = mean_squared_error(y_test, y_pred)
#r2_et = r2_score(y_test, y_pred)
#rmse_et = mean_squared_error(y_test, y_pred, squared=False)

#print("MSE_XTree_irceline:", mse_et)
#print("R2_XTree_irceline:", r2_et)
#print("Rmse_XTree_irceline:", rmse_et)

"""#**Contraintes sur le modèle**

Pour ajuster le modèle de Random Forest Regressor en ajoutant des contraintes, nous pouvons modifier certains paramètres pour éviter un surajustement et potentiellement améliorer les performances sur l'ensemble de test. Voici quelques paramètres que nous pourrions ajuster :
 -	**n_estimators :** Augmenter le nombre d'arbres peut améliorer la performance du modèle jusqu'à un certain point, mais cela augmente aussi le temps de calcul.
 -	**max_depth :** Réduire la profondeur maximale de chaque arbre peut aider à prévenir le surajustement.
 -	**min_samples_split :** Augmenter le nombre minimum d'échantillons requis pour diviser un nœud interne.
 -	**min_samples_leaf :** Augmenter le nombre minimum d'échantillons requis pour être à un nœud feuille.
 -	**max_features :** Réduire le nombre de caractéristiques à considérer lors de la recherche de la meilleure division peut aider à rendre le modèle plus robuste.
"""

# Définir les modèles et leurs grilles d'hyperparamètres respectives
from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
X_train, X_test, y_train, y_test = train_test_split(x_training_meth1, y_training_meth1, test_size = 0.25, random_state = 0)
models = {
    'Linear Regression': (LinearRegression(), {}),
    'Random Forest': (RandomForestRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Extremely Randomized Trees': (ExtraTreesRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Decision Tree': (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}),
    'Gradient Boosting': (GradientBoostingRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'learning_rate': [0.1, 0.01, 0.001]})
}

# Créer des dictionnaires vides pour stocker les meilleurs modèles, leurs métriques d'évaluation et les paramètres utilisés
best_models = {}
best_rmse = {}
best_r2 = {}
used_parameters = {}

# Effectuer un grid search pour chaque modèle
for model_name, (model, param_grid) in models.items():
    grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')

    #
    with tqdm(total=len(param_grid), desc=f"Grid Search ({model_name})", unit="param") as pbar:
        grid_search.fit(X_train, y_train)

        # Save the best model
        best_models[model_name] = grid_search.best_estimator_

        # Save the used parameters
        used_parameters[model_name] = grid_search.best_params_

        # Predict on the test set
        y_pred = grid_search.predict(X_test)

        # Calculate evaluation metrics
        mse = msef(y_test, y_pred)
        rmse = np.sqrt(mse)
        mae = maef(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        # Store the evaluation metrics
        best_rmse[model_name] = rmse
        best_r2[model_name] = r2

        # Print the evaluation metrics
        print(f"Model: {model_name}")
        print("Best Hyperparameters:", grid_search.best_params_)
        print("MSE:", mse)
        print("RMSE:", rmse)
        print("MAE:", mae)
        print("R2 Score:", r2)
        print()

        # Update the progress bar
        pbar.update()

# Sort the best models based on RMSE and R2 score
sorted_models_by_rmse = sorted(best_models.items(), key=lambda x: best_rmse[x[0]])
sorted_models_by_r2 = sorted(best_models.items(), key=lambda x: best_r2[x[0]])

# Print the best models sorted by RMSE
print("Best Models (sorted by RMSE):")
for model_name, model in sorted_models_by_rmse:
    print(f"{model_name}: RMSE = {best_rmse[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

# Print the best models sorted by R2 score
print("\nBest Models (sorted by R2 Score):")
for model_name, model in sorted_models_by_r2:
    print(f"{model_name}: R2 Score = {best_r2[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
# Ajustement du modèle en réduisant max_depth
rf_model_reduced_depth = RandomForestRegressor(n_estimators=200, # Nombre d'arbres
                                               max_depth=15, # Réduction de la profondeur de chaque arbre
                                               min_samples_split=10, # Nombre minimum d'échantillons pour diviser un nœud
                                               min_samples_leaf=4, # Nombre minimum d'échantillons pour être à un nœud feuille
                                               max_features='sqrt', # Nombre de caractéristiques à considérer pour la meilleure division
                                               random_state=42)

# Entraînement du modèle ajusté avec une profondeur réduite
rf_model_reduced_depth.fit(X_train, y_train)

# Prédiction sur l'ensemble de test avec le modèle à profondeur réduite
y_pred_reduced_depth = rf_model_reduced_depth.predict(X_test)

# Évaluation du modèle à profondeur réduite
mse_reduced_depth = mean_squared_error(y_test, y_pred_reduced_depth)
mae_reduced_depth = mean_absolute_error(y_test, y_pred_reduced_depth)
r2_reduced_depth = r2_score(y_test, y_pred_reduced_depth)

mse_reduced_depth, mae_reduced_depth, r2_reduced_depth

# Ajustement du modèle en augmentent le n_estimators
rf_model_adjusted = RandomForestRegressor(n_estimators=300, # Augmenter le nombre d'arbres
                                          max_depth=10, # Limiter la profondeur de chaque arbre
                                          min_samples_split=10, # Nombre minimum d'échantillons pour diviser un nœud
                                          min_samples_leaf=4, # Nombre minimum d'échantillons pour être à un nœud feuille
                                          max_features='sqrt', # Nombre de caractéristiques à considérer pour la meilleure division
                                          random_state=42)
# Entraînement du modèle ajusté
rf_model_adjusted.fit(X_train, y_train)

# Prédiction sur l'ensemble de test avec le modèle à profondeur réduite
y_pred_adjusted = rf_model_adjusted.predict(X_test)

# Évaluation du modèle à profondeur réduite
mse_adjusted = mean_squared_error(y_test, y_pred_adjusted)
mae_adjusted = mean_absolute_error(y_test, y_pred_adjusted)
r2_adjusted = r2_score(y_test, y_pred_adjusted)

mse_adjusted, mae_adjusted, r2_adjusted

"""Contraintes sur basse des connaissances d'un expert"""

# Création de nouvelles caractéristiques basées sur Feature Engineering

# 1. Interaction entre la température et l'humidité
X_train_fe = x_training_meth1.copy(deep=True)
X_test_fe = X_test.copy(deep=True)
X_train_fe['temp_humidity_interaction'] = X_train_fe['Temperature'] * X_train_fe['Humidity']
X_test_fe['temp_humidity_interaction'] = X_test_fe['Temperature'] * X_test_fe['Humidity']

# 2. Transformation de la vitesse du vent pour capturer des effets non linéaires
# Utilisation de la racine carrée comme exemple simple de transformation non linéaire
X_train_fe['O3'] = X_train_fe['O3'] ** 0.5
X_test_fe['Temperature'] = X_test_fe['Temperature'] ** 0.5

# Affichage des premières lignes du dataset transformé pour vérifier les nouvelles caractéristiques
X_train_fe.head()

X_train_fe.shape

y_training_meth1 = df_entrain_meth1["NO2"]
y_training_meth1.shape

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# 1. Interaction entre la température et l'humidité
X_train_fe = x_training_meth1.copy(deep=True)
X_test_fe = X_test.copy(deep=True)
X_train_fe['temp_humidity_interaction'] = X_train_fe['Temperature'] * X_train_fe['Humidity']
X_test_fe['temp_humidity_interaction'] = X_test_fe['Temperature'] * X_test_fe['Humidity']

# 2. Transformation de la vitesse du vent pour capturer des effets non linéaires
# Utilisation de la racine carrée comme exemple simple de transformation non linéaire
X_train_fe['O3'] = X_train_fe['O3'] ** 0.5
X_test_fe['Temperature'] = X_test_fe['Temperature'] ** 0.5

X_t, X_ts, y_t, y_ts = train_test_split(X_train_fe, y_training_meth1, test_size=0.3, random_state=42)

# Creating and training the Extra Trees model
extra_trees_model = ExtraTreesRegressor(random_state=42)
extra_trees_model.fit(X_t, y_t)

# Making predictions and evaluating the model
y3_pred_extra_trees = extra_trees_model.predict(X_ts)
mse_extra_trees = msef(y_ts, y3_pred_extra_trees)
r2_extra_trees = r2_score(y_ts, y3_pred_extra_trees)
rmse_extra_trees = msef(y_ts, y3_pred_extra_trees, squared=False)

print("MSE_ExTree:", mse_extra_trees)
print("R^2_ExTree:", r2_extra_trees)
print("RMSE_ExTree:", rmse_extra_trees)

df_entrain_meth1

df_HVoc_interpolation

df_HVoc_interpolation = df_HVoc_interpolation.drop(columns=['datetime', 'OX', 'NO'])

df_HVoc_interpolation

df_entrain_meth1['type_capteur'] = 0

df_entrain_meth1

df_HVoc_interpolation['type_capteur'] = 1

df_HVoc_interpolation

df_HVoc_interpolation.isnull().sum()

from sklearn.utils import shuffle

# Concaténation des DataFrames en un seul DataFrame
df_combined = pd.concat([df_entrain_meth1, df_HVoc_interpolation], ignore_index=True)
#df_combined = pd.concat([df_entrain_meth1, df_HVoc_interpolation], axis=1)

# Utiliser la fonction shuffle pour mélanger les données
#df_shuffled = shuffle(df_combined).reset_index(drop=True)
df_shuffled = shuffle(df_combined, random_state=42)  # Le random_state est optionnel pour la reproductibilité


print(df_shuffled)

#comparison using two y axis
x = np.arange(0, 30.0, 0.1)
y1 = np.array(df_HVoc['NO2'][4600:4900])
y2 = np.array(df_shuffled['NO2'][4601:4901])

fig, ax1 = plt.subplots()

ax2 = ax1.twinx()
ax1.plot(x, y1, 'g-')
ax2.plot(x, y2, 'b-')

ax1.set_xlabel('X data')
ax1.set_ylabel('NO2 VocSens', color='g')
ax2.set_ylabel('NO2 Irceline', color='b')

plt.show()

x_rf = df_shuffled.drop(columns=['NO2'])  # Predictor variables
y_rf = df_shuffled["NO2"]                             # Target variable

x_rf.isnull().sum()

from sklearn.metrics import mean_absolute_error, mean_squared_error as msef, r2_score
# Division des données en ensembles d'entraînement et de test
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(x_rf, y_rf, test_size=0.2, random_state=42)

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = msef(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

"""**test le model entrainer sur les données melagé sur les donne de test ( vocsens )**"""

# Division des données en ensembles d'entraînement et de test
X_rf_train = x_rf
X_rf_test = df_HVoc_interpolation.drop(columns=['NO2'])
y_rf_train = y_rf
y_rf_test = df_HVoc_interpolation["NO2"]

# Initialisation du modèle de forêt aléatoire
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf.fit(X_rf_train, y_rf_train)

# Prédiction sur l'ensemble de test
y_rf_pred_rf = rf.predict(X_rf_test)

# Calcul de l'erreur quadratique moyenne (MSE)
mse_rf = mean_squared_error(y_rf_test, y_rf_pred_rf)
r2 = r2_score(y_rf_test, y_rf_pred_rf)
rmse = mean_squared_error(y_rf_test, y_rf_pred_rf, squared=False)

print("MSE_RF:", mse_rf)
print("RMSE_RF:", rmse)
print("R^2_RF:", r2)

"""**Introduction des contraintes expert**"""

# Création d'une nouvelle caractéristique(feature) basée sur les connaissances expertes
X_train_expert = x_rf.copy(deep=True)
X_test_expert = df_HVoc_interpolation.drop(columns=['NO2']).copy(deep=True)
y_trainn = y_rf.copy(deep=True)
y_rf_test = df_HVoc_interpolation["NO2"]


# Appliquer la règle : Si la température est inférieure à 5°C, l'effet de l'humidité sur NO2 est doublé
X_train_expert['temp_humidity_interaction'] = X_train_expert.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)
X_test_expert['temp_humidity_interaction'] = X_test_expert.apply(lambda row: row['Humidity'] * 2 if row['Temperature'] < 5 else row['Humidity'], axis=1)

# Réentraînement du modèle de Random Forest avec la nouvelle caractéristique
rf_model_with_expert = RandomForestRegressor(n_estimators=400, # Nombre d'arbres
                                             max_depth=8, # Réduire la profondeur maximale de chaque arbre
                                             min_samples_split=25, # Augmenter le nombre minimum d'échantillons pour diviser un nœud
                                             min_samples_leaf=12, # Augmenter le nombre minimum d'échantillons pour être à un nœud feuille
                                             max_features='sqrt', # Nombre de caractéristiques à considérer pour la meilleure division
                                             random_state=42)

# Entraînement du modèle ajusté avec la nouvelle caractéristique
rf_model_with_expert.fit(X_train_expert, y_trainn)

# Prédiction sur l'ensemble de test avec la nouvelle caractéristique
y_pred_with_expert = rf_model_with_expert.predict(X_test_expert)

# Évaluation du modèle avec la nouvelle caractéristique
mse_with_expert = mean_squared_error(y_rf_test, y_pred_with_expert)
r2 = r2_score(y_rf_test, y_pred_with_expert)
rmse = mean_squared_error(y_rf_test, y_pred_with_expert, squared=False)
print("MSE_RF:", mse_rf)
print("R^2_RF:", r2)
print("RMSE_RF:", rmse)

"""**Contrainte sur l'architecture du modèle**"""

from sklearn.metrics import mean_absolute_error as maef, mean_squared_error as msef, r2_score
X_train = x_rf.copy(deep=True)
X_test = df_HVoc_interpolation.drop(columns=['NO2']).copy(deep=True)
y_train = y_rf.copy(deep=True)
y_test = df_HVoc_interpolation["NO2"]

# Define the models and their respective hyperparameter grids
#X_train, X_test, y_train, y_test = train_test_split(x_rf, y_rf, test_size=0.2, random_state=42)
models = {
    'Linear Regression': (LinearRegression(), {}),
    'Random Forest': (RandomForestRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Extremely Randomized Trees': (ExtraTreesRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'max_depth': [None, 5, 10]}),
    'Decision Tree': (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}),
    'Gradient Boosting': (GradientBoostingRegressor(), {'n_estimators': [25, 50, 100, 200, 300], 'learning_rate': [0.1, 0.01, 0.001]})
}

# Create empty dictionaries to store the best models, their evaluation metrics, and used parameters
best_models = {}
best_rmse = {}
best_r2 = {}
used_parameters = {}

# Perform grid search for each model
for model_name, (model, param_grid) in models.items():
    grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')

    # Wrap the grid search loop with tqdm for progress bar
    with tqdm(total=len(param_grid), desc=f"Grid Search ({model_name})", unit="param") as pbar:
        grid_search.fit(X_train, y_train)

        # Save the best model
        best_models[model_name] = grid_search.best_estimator_

        # Save the used parameters
        used_parameters[model_name] = grid_search.best_params_

        # Predict on the test set
        y_pred = grid_search.predict(X_test)

        # Calculate evaluation metrics
        mse = msef(y_test, y_pred)
        rmse = np.sqrt(mse)
        mae = maef(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        # Store the evaluation metrics
        best_rmse[model_name] = rmse
        best_r2[model_name] = r2

        # Print the evaluation metrics
        print(f"Model: {model_name}")
        print("Best Hyperparameters:", grid_search.best_params_)
        print("MSE:", mse)
        print("RMSE:", rmse)
        print("MAE:", mae)
        print("R2 Score:", r2)
        print()

        # Update the progress bar
        pbar.update()

# Sort the best models based on RMSE and R2 score
sorted_models_by_rmse = sorted(best_models.items(), key=lambda x: best_rmse[x[0]])
sorted_models_by_r2 = sorted(best_models.items(), key=lambda x: best_r2[x[0]])

# Print the best models sorted by RMSE
print("Best Models (sorted by RMSE):")
for model_name, model in sorted_models_by_rmse:
    print(f"{model_name}: RMSE = {best_rmse[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

# Print the best models sorted by R2 score
print("\nBest Models (sorted by R2 Score):")
for model_name, model in sorted_models_by_r2:
    print(f"{model_name}: R2 Score = {best_r2[model_name]:.4f}")
    print("Used Parameters:", used_parameters[model_name])
    print()

feature_importances = rf.feature_importances_
print(f'Feature importances: {feature_importances}')

# Accessing the individual trees in the random forest
trees = rf.estimators_

tree_depths = [tree.tree_.max_depth for tree in trees]

# Print the depth of each tree
for i, depth in enumerate(tree_depths):
    print(f"Tree {i+1} depth: {depth}")

# Select one of the trees from the random forest (e.g., the first tree)
from sklearn import tree

tree_to_plot = rf.estimators_[0]

# Plot the selected tree
fig, ax = plt.subplots(figsize=(10, 10))
tree.plot_tree(tree_to_plot, ax=ax, max_depth=2)
plt.show()